In [7]:
 #numerical python

In [8]:
import numpy as np

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("G:\Mi unidad\DATASETS\prueba_categoricas.csv")

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\jesic\AppData\Local\Temp\ipykernel_1732\3330832351.py:1: SyntaxWarning: invalid escape sequence '\M'
  df = pd.read_csv("G:\Mi unidad\DATASETS\prueba_categoricas.csv")


In [11]:
df.head(10)

Nombre  Edad     Género     Ciudad  Ingreso
0     Ana    23   Femenino     Madrid    30000
1    Luis    34  Masculino  Barcelona    40000
2  Carlos    45  Masculino     Madrid    50000
3   Maria    29   Femenino   Valencia    35000
4   Pedro    56  Masculino    Sevilla    60000

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Nombre   5 non-null      object
 1   Edad     5 non-null      int64 
 2   Género   5 non-null      object
 3   Ciudad   5 non-null      object
 4   Ingreso  5 non-null      int64 
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes


In [13]:
#promedio de poblacion de todas las ciudades
df['Ingreso'].mean()

np.float64(43000.0)

In [14]:
#promedio de visitantes  de todas las ciudades
df['Edad'].mean()

np.float64(37.4)

In [15]:
np.round(df['Ingreso'].mean()) #Evenly round to the given number of decimals. Redondear uniformemente al número dado de decimales.

np.float64(43000.0)

In [16]:
df['Edad'].min()

np.int64(23)

In [53]:
df1 = pd.read_csv("G:/Mi unidad/DATASETS/20231205_info_publica_datos_barrios.csv")
df1

id_renabap             nombre_barrio     provincia departamento  \
0              1               Monterrey I  Buenos Aires        Pilar   
1              2               Malvinas II  Buenos Aires     La Plata   
2              3               Ferroviario  Buenos Aires     La Plata   
3              4               La Favelita  Buenos Aires     La Plata   
4              5                    Casaca  Buenos Aires     La Plata   
...          ...                       ...           ...          ...   
6462        6862               Ferroviario       Tucumán    Cruz Alta   
6463        6863            Pacará Pintado       Tucumán    Cruz Alta   
6464        6864             Villa Rosario       Tucumán        Lules   
6465        6865  Ampliación 130 viviendas       Tucumán      Capital   
6466        6866          Virgen Del Valle       Tucumán   Tafí Viejo   

                  localidad  cantidad_viviendas_aproximadas  \
0         Presidente Derqui                              40   
1       José Melchor Romero                             290   
2          Angel Etcheverry                             133   
3                    Tolosa                             122   
4                 City Bell                              20   
...                     ...                             ...   
6462              Las Cejas                             160   
6463             San Andrés                              20   
6464      Ingenio San Pablo                              45   
6465  San Miguel De Tucumán                              19   
6466            Las Talitas                              35   

      cantidad_familias_aproximada decada_de_creacion  anio_de_creacion  \
0                               44        Década 1990               NaN   
1                              319        Década 1990               NaN   
2                              146        Década 2000               NaN   
3                              134        Década 1970               NaN   
4                               22        Década 2000               NaN   
...                            ...                ...               ...   
6462                           176        Década 1920               NaN   
6463                            22        Década 2000               NaN   
6464                            50        Década 1990               NaN   
6465                            21        Década 2010            2014.0   
6466                            39        Década 2010            2016.0   

                                      energia_electrica  \
0         Conexión regular a la red con medidor prepago   
1                           Conexión irregular a la red   
2                           Conexión irregular a la red   
3                           Conexión irregular a la red   
4                           Conexión irregular a la red   
...                                                 ...   
6462                        Conexión irregular a la red   
6463  Conexión formal a la red con medidor domicilia...   
6464  Conexión formal a la red con medidor domicilia...   
6465  Conexión formal a la red con medidor domicilia...   
6466                        Conexión irregular a la red   

                         efluentes_cloacales  \
0      Desagüe a cámara séptica y pozo ciego   
1      Desagüe a cámara séptica y pozo ciego   
2     Desagüe sólo a pozo negro/ciego u hoyo   
3     Desagüe sólo a pozo negro/ciego u hoyo   
4      Desagüe a cámara séptica y pozo ciego   
...                                      ...   
6462   Desagüe a cámara séptica y pozo ciego   
6463  Desagüe sólo a pozo negro/ciego u hoyo   
6464  Desagüe sólo a pozo negro/ciego u hoyo   
6465  Desagüe sólo a pozo negro/ciego u hoyo   
6466  Desagüe sólo a pozo negro/ciego u hoyo   

                                    agua_corriente          cocina  \
0               Bomba de agua de pozo domiciliaria  Gas en garrafa   
1              Conexión irregular a la red de

In [54]:
# Identificar columnas con valores nulos
df1.isnull().sum()
#me devuelve los nulos, no modifica el df original

id_renabap                           0
nombre_barrio                        0
provincia                            0
departamento                         0
localidad                            0
cantidad_viviendas_aproximadas       0
cantidad_familias_aproximada         0
decada_de_creacion                   0
anio_de_creacion                  4779
energia_electrica                    0
efluentes_cloacales                  0
agua_corriente                       0
cocina                               0
calefaccion                          0
titulo_propiedad                     0
clasificacion_barrio                 0
superficie_m2                        0
dtype: int64

In [55]:
# Reemplazar valores nulos en esas columnas con la mediana (en este caos conviene asi)
df1['anio_de_creacion'] = df1['anio_de_creacion'].fillna(df1['anio_de_creacion'].median())
df1.head()

id_renabap nombre_barrio     provincia departamento            localidad  \
0           1   Monterrey I  Buenos Aires        Pilar    Presidente Derqui   
1           2   Malvinas II  Buenos Aires     La Plata  José Melchor Romero   
2           3   Ferroviario  Buenos Aires     La Plata     Angel Etcheverry   
3           4   La Favelita  Buenos Aires     La Plata               Tolosa   
4           5        Casaca  Buenos Aires     La Plata            City Bell   

   cantidad_viviendas_aproximadas  cantidad_familias_aproximada  \
0                              40                            44   
1                             290                           319   
2                             133                           146   
3                             122                           134   
4                              20                            22   

  decada_de_creacion  anio_de_creacion  \
0        Década 1990            2014.0   
1        Década 1990            2014.0   
2        Década 2000            2014.0   
3        Década 1970            2014.0   
4        Década 2000            2014.0   

                               energia_electrica  \
0  Conexión regular a la red con medidor prepago   
1                    Conexión irregular a la red   
2                    Conexión irregular a la red   
3                    Conexión irregular a la red   
4                    Conexión irregular a la red   

                      efluentes_cloacales  \
0   Desagüe a cámara séptica y pozo ciego   
1   Desagüe a cámara séptica y pozo ciego   
2  Desagüe sólo a pozo negro/ciego u hoyo   
3  Desagüe sólo a pozo negro/ciego u hoyo   
4   Desagüe a cámara séptica y pozo ciego   

                                 agua_corriente          cocina  \
0            Bomba de agua de pozo domiciliaria  Gas en garrafa   
1           Conexión irregular a la red de agua  Gas en garrafa   
2  Conexión formal a la red de agua con factura  Gas en garrafa   
3           Conexión irregular a la red de agua  Gas en garrafa   
4            Bomba de agua de pozo domiciliaria  Gas en garrafa   

         calefaccion titulo_propiedad clasificacion_barrio  superficie_m2  
0          Sin Datos               NO         Asentamiento          11674  
1      Leña o carbón               NO         Asentamiento          98093  
2      Leña o carbón               NO         Asentamiento          75887  
3  Energía eléctrica               NO         Asentamiento          36889  
4          Sin Datos               NO         Asentamiento          25768

In [61]:
# Identificar columnas con valores nulos
df1.isnull().sum()

id_renabap                        0
nombre_barrio                     0
provincia                         0
departamento                      0
localidad                         0
cantidad_viviendas_aproximadas    0
cantidad_familias_aproximada      0
decada_de_creacion                0
anio_de_creacion                  0
energia_electrica                 0
efluentes_cloacales               0
agua_corriente                    0
cocina                            0
calefaccion                       0
titulo_propiedad                  0
clasificacion_barrio              0
superficie_m2                     0
dtype: int64

In [57]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6467 entries, 0 to 6466
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id_renabap                      6467 non-null   int64  
 1   nombre_barrio                   6467 non-null   object 
 2   provincia                       6467 non-null   object 
 3   departamento                    6467 non-null   object 
 4   localidad                       6467 non-null   object 
 5   cantidad_viviendas_aproximadas  6467 non-null   int64  
 6   cantidad_familias_aproximada    6467 non-null   int64  
 7   decada_de_creacion              6467 non-null   object 
 8   anio_de_creacion                6467 non-null   float64
 9   energia_electrica               6467 non-null   object 
 10  efluentes_cloacales             6467 non-null   object 
 11  agua_corriente                  6467 non-null   object 
 12  cocina                          64

In [64]:
fc = df1[df1['nombre_barrio'].isin(['Ferroviario', 'Casaca'])]
#me devuelve las series en las q el nombre del barrio es Ferroviario o Casaca
print(fc.cocina) #imprimo la columna cocina de las series anteriores

2                                    Gas en garrafa
4                                    Gas en garrafa
277                                  Gas en garrafa
650                                  Gas en garrafa
2009    Conexión formal a la red de gas con factura
3963                                 Gas en garrafa
5038                                  Leña o carbón
5290                                 Gas en garrafa
5352                                  Leña o carbón
5379                                 Gas en garrafa
5913    Conexión formal a la red de gas con factura
6462                                 Gas en garrafa
Name: cocina, dtype: object


In [65]:
df1.count() #cuenta los valores no nulos de cada columna

id_renabap                        6467
nombre_barrio                     6467
provincia                         6467
departamento                      6467
localidad                         6467
cantidad_viviendas_aproximadas    6467
cantidad_familias_aproximada      6467
decada_de_creacion                6467
anio_de_creacion                  6467
energia_electrica                 6467
efluentes_cloacales               6467
agua_corriente                    6467
cocina                            6467
calefaccion                       6467
titulo_propiedad                  6467
clasificacion_barrio              6467
superficie_m2                     6467
dtype: int64

In [66]:
fc.nombre_barrio.value_counts() #cuenta cuantas veces aparece cada valor en la columna nombre_barrio

nombre_barrio
Ferroviario    11
Casaca          1
Name: count, dtype: int64

In [69]:
fc.cantidad_familias_aproximada
#me devuelve solo la columna cantidad_familias_aproximada de las series anteriores

2       146
4        22
277      33
650     116
2009     40
3963     22
5038     22
5290     17
5352     50
5379     55
5913     44
6462    176
Name: cantidad_familias_aproximada, dtype: int64

In [70]:
fc['cocina'].value_counts()

cocina
Gas en garrafa                                 8
Conexión formal a la red de gas con factura    2
Leña o carbón                                  2
Name: count, dtype: int64

** ARRAYS **

In [72]:
#CREACION ARRAY CON NUNPY
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [73]:
len(my_array)

5

In [20]:
my_array.size

5

In [74]:
#DIMENSIONES DEL ARRAY
my_array.ndim

1

In [76]:
array_triple = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array_triple

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [78]:
array_triple.ndim #me devuelve la cantidad de dimensiones

3

In [80]:
array_triple.shape #me devuelve la forma del array
#(2,2,3) 2 matrices de 2 filas y 3 columnas

(2, 2, 3)

In [81]:
#DATA TYPE DEL ARRAY
array_triple.dtype

dtype('int64')

MANIPULACION DE ARRAYS

OPERACIONES CON ARRAYS

In [82]:
my_array
print('Array original : ',my_array)

Array original :  [1 2 3 4 5]


In [84]:
array_nuevo = my_array * 100 #multiplico cada elemento del array por 100
print('Array multiplicado por 100 : ',array_nuevo)

Array multiplicado por 100 :  [100 200 300 400 500]


In [87]:
array_veintes = np.array( [20,40,60,80,100 ] )#
print('Array veintes : ',array_veintes)

Array veintes :  [ 20  40  60  80 100]


SUMO A UN ARRAY OTRO ARRAY

In [88]:
array_nuevo1 = my_array + array_veintes
print('Array nuevo1 : ',array_nuevo1)

Array nuevo1 :  [ 21  42  63  84 105]


In [89]:
#CAMBAR TIIPO DE DATO
a = np.array ([1,2,3])
a.dtype

dtype('int64')

CAMBIO TIPO DE DATO

In [90]:
b = np.array ([1,2,3], dtype=float)
b.dtype

dtype('float64')

In [91]:
b #cambie a flotando los nros declarados enteros

array([1., 2., 3.])

In [94]:
c = np.array ([1,0,3,0,0,293332], dtype=bool)
c #CREO UN ARRAY DE BOOLEANOS

array([ True, False,  True, False, False,  True])

In [95]:
c = np.array ([1,0,3], dtype=complex)
c

array([1.+0.j, 0.+0.j, 3.+0.j])

CREACION DE ARRAYS

In [96]:
#CON RANGO
n = np.arange(10)
n#crea un array de 0 a 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#RANGO CON SALTOS
n = np.arange(10,20,2)
n
#10 a 20 de a 2

array([10, 12, 14, 16, 18])

In [41]:
# ARREGLOS DE ZEROS
n = np.zeros(10)
n

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
n = np.zeros(10, dtype=int)
n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
#ARREGLOS DE UNOS
n = np.ones(10)
n

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
#ARREGLO A PARTIR E DATOS BASURA, SIRVE PARA RESERVAR EL ESPACIO EN MEMORIA, LUEGO PODEMOS MODIFICARLOS
q = np.empty(10) #crea un array de 10 elementos con datos basura
q

array([0.0000e+000, 4.9407e-324, 9.8813e-324, 1.4822e-323, 1.9763e-323,
       3.1927e-320, 3.1931e-320, 3.1936e-320, 3.1941e-320, 3.1946e-320])

In [45]:
#ARREGLOS DE NROS ENTEROS ALEATORIOS
r = np.random.randint(20, size=10)
r

array([6, 0, 1, 8, 2, 8, 8, 5, 8, 9])

In [46]:
a = np.random.randint(25,30,10)
a
#NROS RANDOM DE X A Y, Z CANT

array([28, 29, 29, 25, 25, 27, 26, 29, 28, 27])

In [47]:
#MODIFICAR VALORES DESDE EL INDICE
a[0] = 1000
a

array([1000,   29,   29,   25,   25,   27,   26,   29,   28,   27])

In [48]:
#GENERAR SUB ARREGLOS PARTIENDO DE UN ARREGLO ORIGINAL
# A[START:END:SALTOS]
t = a[1:5]
t

array([29, 29, 25, 25])

In [49]:
#OMITO DECLARAR EL CERO, SALTO DE 2 EN 2
y = a[:8:2]
y

array([1000,   29,   25,   26])

In [60]:
#VECTORIZAR
a = np.random.randint(0,10,20)
a

array([3, 8, 6, 4, 9, 1, 8, 6, 2, 1, 4, 1, 3, 7, 6, 7, 0, 5, 9, 4])

In [67]:
def operacion(valor):
  return (valor + 2) +10

operacion(3)

15

In [68]:
for valor in a:
  print(operacion(valor))

15
20
18
16
21
13
20
18
14
13
16
13
15
19
18
19
12
17
21
16


In [72]:
#FUNCION VECTORIZAR PARA CUANDO TENGO MUCHOS VALORES

vector = np.vectorize(operacion) #cre un valor desde los valores que devuelve la funcion operacion
vector (a) #asigno a ese vector (q a su vez se asigna a una funcion) los valores demi array a

array([15, 20, 18, 16, 21, 13, 20, 18, 14, 13, 16, 13, 15, 19, 18, 19, 12,
       17, 21, 16])

In [73]:
b = np.random.randint(100,150,20)
b

array([149, 109, 126, 141, 107, 143, 102, 137, 124, 149, 128, 104, 137,
       110, 136, 113, 136, 112, 138, 137])

In [74]:
vector2 = np.vectorize(operacion)
vector2(b)

array([161, 121, 138, 153, 119, 155, 114, 149, 136, 161, 140, 116, 149,
       122, 148, 125, 148, 124, 150, 149])

In [78]:
#CREO FUNCION LAMBDA (lambda parámetro: OPERACION Q DEVUELVE))
vector3 = np.vectorize(lambda x: x+200)
vector4 =vector3(b) #APLICO LA FUNCION ELEMENTO POR ELEMENTO DE b
vector4

array([349, 309, 326, 341, 307, 343, 302, 337, 324, 349, 328, 304, 337,
       310, 336, 313, 336, 312, 338, 337])

In [88]:
#CONCATENACION DE ARRAYS

In [50]:
x =[1,2,3]
y = [4,5,6]
z = [7,8,9]

In [51]:
juntos = np.concatenate([x,y,z])
juntos

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a =[[1,2,3],[4,5,6]]
b =[[7,8,9],[10,11,12]]
c = [[13,14,15],[16,17,18]]
d = [[19,20,21],[22,23,24]]
e=[[25,26,27],[28,29,30]]

array_concatenado= np.concatenate([a,b,c,d,e], axis=0) #AXIS 1 EJE X, AXIS 0 EJE Y


In [87]:
print(array_concatenado)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]


In [53]:
np.concatenate([a,b], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
a =[[1,2,3],[4,5,6],[25,26,27],[28,29,30]]
b =[[7,8,9],[10,11,12],[19,20,21],[22,23,24]]

np_hor= np.concatenate([a,b], axis=1) #horizontal
np_hor

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12],
       [25, 26, 27, 19, 20, 21],
       [28, 29, 30, 22, 23, 24]])

In [55]:
np_hor.shape #filas,columnas

(4, 6)

In [56]:
np_ver=np.concatenate([a,b], axis=0) #horizontal
np_ver

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [25, 26, 27],
       [28, 29, 30],
       [ 7,  8,  9],
       [10, 11, 12],
       [19, 20, 21],
       [22, 23, 24]])

In [57]:
np_ver.shape #filas, columnasd

(8, 3)

In [58]:
ar_reshape = np_ver.reshape(3,8)
ar_reshape

array([[ 1,  2,  3,  4,  5,  6, 25, 26],
       [27, 28, 29, 30,  7,  8,  9, 10],
       [11, 12, 19, 20, 21, 22, 23, 24]])